feat: secondary cache loader
expo/entity pull request #123
Opened 2021-04-03 03:21 UTC by wschurman

# Why

This is the start of an exploration into a secondary cache (cache on top of entity) that allows for arbitrary data caching and retrieval. I'm not yet sure whether this belongs in entity itself at all since really the only dependencies are on authorization calls. I'm going to put more thought into it.

# Test Plan

N/A

2021-05-13 21:07 UTC, jkhales approved these changes
Very exciting!

2021-05-14 04:27 UTC, wschurman commented on packages/entity-cache-adapter-redis/src/GenericRedisCacher.ts
> +const DOES_NOT_EXIST_REDIS = '';
Mostly historical reasons (it was used in the old models cacher framework). Unfortunately we can't change it though without invalidating all caches.

2021-05-14 04:27 UTC, wschurman commented on packages/entity-secondary-cache-redis/CHANGELOG.md
> +See [Conventional Commits](https://conventionalcommits.org) for commit guidelines.
So far it has worked decently well for this multi-package repo but I could see it being too opinionated for repos like expo/expo.

2021-05-14 04:27 UTC, wschurman commented on packages/entity-secondary-cache-redis/src/RedisSecondaryEntityCache.ts
> +      });
The GenericRedisCacher wraps all calls to redis in `wrapNativeRedisCall`, which for now assumes every error at that layer is transient and throws as such.

At this point in the stack there have been no errors at the redis layer, and the only errors that could be thrown here are programmer errors (errors in this code itself).

2021-05-20 08:40 UTC, ide requested changes
In a subset of cases where we have unique composite keys (`UNIQUE (a, b)`), we could tell the Entity framework that the pair `(a, b)` is cacheable and have the cache invalidated when the same way single-field keys get their cache entries invalidated. I think this autoinvalidation could be built on top of the more flexible, generic secondary cacher in this PR.

(Autoinvalidation would not work for the case like "ORDER BY created_at DESC LIMIT 1" where there is no unique key.)

I think it is good the secondary cache has a separate TTL. We always can pass in the same TTL as the main cache adapter context.

2021-05-20 08:40 UTC, ide commented on packages/entity/src/__tests__/EntitySecondaryCacheLoader-test.ts
> +    it('calls invalidate on the secondary cache loader', async () => {
```suggestion
    it('calls invalidate on the secondary cache', async () => {
```
(the test is already for the loader)

2021-05-20 08:40 UTC, ide commented on packages/entity-secondary-cache-redis/src/__integration-tests__/RedisSecondaryEntityCache-integration-test.ts
> +      },
Think we should spy on this or make it throw since it shouldn't be called in the secondary loader tests?

2021-05-25 00:32 UTC, wschurman commented on packages/entity-cache-adapter-redis/src/RedisCacheAdapter.ts
> +      invariant(fieldsKey, 'Invalid key returned from generic redis cacher');
Good catch. I'll add some test cases for this as well.

2021-05-25 00:46 UTC, wschurman commented on packages/entity-secondary-cache-redis/src/RedisSecondaryEntityCache.ts
> +      });
That's a good question, and one I hadn't really considered. The fetcher is `fetchObjectsFromDatabaseAsync`, and I _think_ the cleaner implementation is to treat any returned value that is not a entity fields object as a miss, so we should treat null, undefined, and not in the map the same.

2021-05-25 01:20 UTC, ide commented on packages/entity-secondary-cache-redis/src/RedisSecondaryEntityCache.ts
> +      });
should be safe and not create issues down the road:
```
const fetchMisses = loadParamsToFetch.filter((loadParams) => fetchResults.get(loadParams) == null);
```

2021-05-25 03:32 UTC, wschurman commented
> In a subset of cases where we have unique composite keys (`UNIQUE (a, b)`), we could tell the Entity framework that the pair `(a, b)` is cacheable and have the cache invalidated when the same way single-field keys get their cache entries invalidated. I think this autoinvalidation could be built on top of the more flexible, generic secondary cacher in this PR.
> 
> (Autoinvalidation would not work for the case like "ORDER BY created_at DESC LIMIT 1" where there is no unique key.)

To accomplish this I think a generalized approach would be better than separate implementation. I could see it being done by factoring out what already exists in the loader into things like `loadByFieldsCompositeKey(Tuple<FieldName, FieldValue>[])` and then make `loadByFieldEqualing` the n=1 case that calls into it (and doing similar conversions for other existing methods). The tough thing will be figuring out how to invalidate the case where sub-columns of composite keys are themselves unique and cache keys (or disallowing this).

2021-05-25 03:40 UTC, ide approved these changes
The explicit `null`s for lookup misses hopefully will be useful, especially from a typechecking perspective.

2021-05-26 15:52 UTC, merged