feat: allow null field values in loadManyByFieldEqualityConjunctionAsync
expo/entity pull request #130
Opened 2021-06-28 22:42 UTC by wschurman

# Why

A feature request from @jkhales for an API endpoint within the Expo server. 

Since the results for this type of load aren't stored in a dataloader or cached, we can just pipe null fieldValues directly through to the database adapters for load, and it is their duty to handle them for this type of load.

# How

This ended up being slightly more difficult than anticipated but not too bad. Complications:
- `ANY(?)` cannot contain `NULL` so it needs to be split into separate `OR WHERE` but within the same conjunctive clause.
- Replicating the default `NULLS FIRST/LAST` postgres behavior in StubDatabaseAdapter required checking for null explicitly: https://www.postgresql.org/docs/8.3/queries-order.html#:~:text=The-,NULLS%20FIRST,-and%20NULLS%20LAST

# Test Plan

Run tests.

2021-06-28 23:51 UTC, ide requested changes

2021-06-28 23:51 UTC, ide commented on packages/entity/src/utils/testing/__tests__/StubDatabaseAdapter-test.ts
> +                  numberField: 3,
Make this row distinguishable from the row above:
```suggestion
                  customIdField: '4',
                  testIndexedField: 'h4',
                  numberField: 4,
```

2021-06-28 23:51 UTC, ide commented on packages/entity/src/utils/testing/StubDatabaseAdapter.ts
> +        return aField > bField || aField === null
null is ordered somewhere between -1 and 0 when comparing it against integers. I think it is clearer to do the null checks first (if both are null, return 0, if either one is null, return 1 or -1) and then run the regular comparison checks once we know both values are non-null.

As it stands I think this current implementation breaks down with aField = 1, bField = null.

(worth adding a regression test perhaps)

2021-06-29 13:05 UTC, jkhales approved these changes
Wow, quick turn around! Thank you!

2021-06-29 15:34 UTC, ide commented on packages/entity-database-adapter-knex/src/PostgresEntityDatabaseAdapter.ts
> +            builder.orWhere(tableField, null);
Good catch. I agree IS NULL's explicitness is appealing and what I'm used to writing. Maybe knex/pg handles `orWhere(x, null)` as a special case but using the dedicated `orWhereNull` function matches our intent.

2021-06-30 00:31 UTC, ide approved these changes

2021-06-30 00:31 UTC, ide commented on packages/entity/src/utils/testing/StubDatabaseAdapter.ts
> +        return aField > bField || aField === null
At this point we are not guaranteed `aField !== null`:
```suggestion
        return aField > bField
```

2021-06-30 00:31 UTC, ide commented on packages/entity/src/utils/testing/StubDatabaseAdapter.ts
> +        return bField > aField || bField === null
```suggestion
        return bField > aField
```

2021-07-01 17:58 UTC, merged